steps:
  - label: ":hammer: Build and Test"
    command: "echo 'Running Buildkite Step Memo desde el repo'"
  - label: "sleeping"
    command: "sleep 15"
  - label: "after sleep"
    command: "echo 'Im up'"
