steps:
  - label: ":hammer: Build and Test"
    key: "build-test"
    command: "echo 'Running Buildkite Step Memo desde el repo'"

  - label: "I'll run after sleep"
    key: "sleep-5"
    command: "echo 'I ran after sleep and sleep again 5 sec' && sleep 5"

  - label: "Another sleep"
    key: "sleep-10"
    command: "sleep 10"

  - label: "Sleeping"
    key: "sleep-15"
    command: "sleep 15"

  - label: "After sleep"
    key: "after-sleep"
    command: "echo 'I'm up'"
