steps:
  - label: "Fetch annotation flag from SSM"
    command: |
      ENABLE_PUSH_ANNOTATIONS=memo
      echo "SSM value for VAR_ANNOTATIONS is: $ENABLE_PUSH_ANNOTATIONS"
      buildkite-agent meta-data set ENABLE_PUSH_ANNOTATIONS "$ENABLE_PUSH_ANNOTATIONS"

