steps:
  - label: ":hammer: Build and Test"
    command: "echo 'Running Buildkite Step Memo desde el repo'"
  - label: "::ruby: checking git branch"
    command: "cd /home/deploy/placeit && git checkout capistrano && ls -l"
