steps:
  - label: ":hammer: Build and Test"
    command: "echo 'Running Buildkite Step Memo desde el repo'"
  - label: "sleeping"
    command: "sleep 10"
  - label: "after sleep"
    command: "echo 'Im up'"
