steps:
  - label: ":hammer: Build and Test"
    key: 1
    command: "echo 'Running Buildkite Step Memo desde el repo'"

  - label: "echo 'holding next step'"
    key: "waiting"
    command: "sleep 5"

  - label: "after sleep"
    command: "echo 'Im up'"
    depends_on:
      - "waiting"

  - label: "doing nothing"
    command: "echo 'doing nothing'"

  - label: ":package: Load Other Pipeline"
    command: "buildkite-agent sub-pipeline upload"
