steps:
  - label: "Fetch annotation flag from SSM"
    command: ./script/buildkite/test-variable.sh | buildkite-agent pipeline upload
    plugins:
      - seek-oss/ssm#v0.1.0:
          assume-role-arn: "arn:aws:iam::311220801150:role/testingmemossm"
          ssmkey: "TESTING_VAR"
          envvar: "ENABLE_PUSH_ANNOTATIONS"

  - label: "Read annotation flag"
    depends_on: set-annotation-flag
    command: |
      echo "Annotation flag is $ENABLE_PUSH_ANNOTATIONS"
