name: Trigger Buildkite Pipeline

on:
  push:
    branches:
      - main

jobs:
  trigger-buildkite:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Buildkite Agent
        run: |
          curl -L https://raw.githubusercontent.com/buildkite/agent/main/install.sh | sudo bash
          sudo apt-get install -y buildkite-agent

      - name: Trigger Buildkite Pipeline
        env:
          BUILDKITE_AGENT_TOKEN: ${{ secrets.BUILDKITE_AGENT_TOKEN }}
        run: |
          echo "Uploading Buildkite Pipeline"
          buildkite-agent pipeline upload .buildkite/pipeline.yml

