name: Trigger Buildkite Pipeline

on:
  push:
    branches:
      - main

jobs:
  trigger-buildkite:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Buildkite Agent
        run: |
          curl -fsSL https://keys.openpgp.org/vks/v1/by-fingerprint/32A37959C2FA5C3C99EFBC32A79206696452D198 | sudo gpg --dearmor -o /usr/share/keyrings/buildkite-agent-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/buildkite-agent-archive-keyring.gpg] https://apt.buildkite.com/buildkite-agent stable main" | sudo tee /etc/apt/sources.list.d/buildkite-agent.list
          sudo apt-get update && sudo apt-get install -y buildkite-agent

      - name: Trigger Buildkite Pipeline
        env:
          BUILDKITE_AGENT_TOKEN: ${{ secrets.BUILDKITE_AGENT_TOKEN }}
        run: |
          echo "Uploading Buildkite Pipeline"
          export BUILDKITE_JOB_ID=${{ secrets.BUILDKITE_JOB_ID }} 
          export BUILDKITE_AGENT_ACCESS_TOKEN=${{ secrets.BUILDKITE_AGENT_ACCESS_TOKEN }}
          buildkite-agent pipeline upload .buildkite/pipeline.yml

