name: Trigger Buildkite Pipeline

on:
  push:
    branches:
      - main

jobs:
  trigger-buildkite:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Buildkite Agent
        run: |
          sudo apt-get update
          sudo apt-get install -y gnupg
          curl -sL https://apt.buildkite.com/buildkite-agent-stable.gpg | sudo apt-key add -
          echo "deb https://apt.buildkite.com/stable/ stable main" | sudo tee /etc/apt/sources.list.d/buildkite-agent.list
          sudo apt-get update
          sudo apt-get install -y buildkite-agent

      - name: Trigger Buildkite Pipeline
        env:
          BUILDKITE_AGENT_TOKEN: ${{ secrets.BUILDKITE_AGENT_TOKEN }}
        run: |
          echo "Uploading Buildkite Pipeline"
          buildkite-agent pipeline upload .buildkite/pipeline.yml

